### ISSUE TITLE
System.ArgumentException: Invalid map length: 3 is expected, but got 2

### ISSUE THREAD

**Issue by Sing303** [aensidhe/tarantool-csharp#55]
При использовании следующего кода:
```

       private static void Main(string[] args)
        {
            Task<Space> x = HashIndexMethods();
            Console.ReadKey();
        }
        public static async Task<Space> HashIndexMethods()
        {
            var x = new Tarantool.Client.Box(new Tarantool.Client.Model.ConnectionOptions()
            {
                EndPoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 3301)
            });
            await x.Connect();
            var schema = x.GetSchema();
            return await schema.GetSpace("test");
        } 

```

Вылетает exception:
> "System.ArgumentException: Invalid map length: 3 is expected, but got 2.\r\n   в Tarantool.Client.Converters.ResponseHeaderConverter.Read(IMsgPackReader reader) в D:\\Downloads\\tarantool-csharp-master\\src\\tarantool.client\\Converters\\ResponseHeaderConverter.cs:строка 40"

Стек: http://pastebin.com/9ixQAgTw
При запуске тарантула версия следующая: /usr/bin/tarantool: version 1.6.3-539-g211672f

**Comment by aensidhe** [comment]
@Sing303 update nuget package to latest version. But tarantool developers recommend you to update your version of tarantool.
